package ie.gmit.sw;

public enum Algorithms {
	DAMERAU_LEVENSHTEIN_DISTANCE,
	EUCLIDEAN_DISTANCE,
	HAMMING_DISTANCE,
	HIRSCHBERG_ALGORITHM,
	JARO_WINKLER_DISTANCE,
	LEVENSHTEIN_DISTANCE,
	NEEDLEMAN_WUNSCH,
	SMITH_WATERMAN
}